### ISSUE TITLE
Visnetwork rendering speed too slow

### ISSUE THREAD

**Issue by yjunechoe** [yjunechoe/Snowglobe#22]
cut down time on processing (tooltip might be overkill) or trigger data preparation in the background

**Comment by mcweenysean** [comment]
since this demo is coming up in less than a week, I'm commenting out wordcloud and network viz, as they can both freeze the app when they bug. I don't have time this week to do proper error handling so this is the short term fix.

**Comment by yjunechoe** [comment]
Sounds good. This might just have to be rehauled entirely at some point anyways, so I'll close this and open a new issue when I get to it
