### ISSUE TITLE
Missing row? Next row issue in staging

### ISSUE THREAD

**Issue by mcweenysean** [yjunechoe/Snowglobe#30]
Tried to stage a file of 52 inputs for the validation paper. 3 theses were not found. Should have staged 49 papers, but only staged 46. Nothing seemed weird about the three that weren't staged after checking ```scrape()``` and ```snowball()```, so I tried to stage them from a different file, and they had no problem staging for a total of 49 between the two uploaded files.

Deleted the three theses from the list of 52, and the 49 titles stage no problem. True in both old patch (online) and new patch (in R on local).

I moved the theses to the end of the file and it staged all 49, and when leaving one thesis in it stages 48, failing to stage the next row, even though it was technically found. I added a blank row, and the following row's paper did not stage. So wherever we have a missing row, it will not stage the following row. Should be a relatively easy fix

**Comment by yjunechoe** [comment]
Looks like there was another duplicate removal step triggered by the "Confirm" button that filtered the searched inputs by row indices, which was causing the issue. The improved error handling from 7c2d5f6c94711fe83b830ec2a642fbc5b18348e7 already takes care of duplicates at the search step and does it better, so the old duplicate removal step is redundant. Should be fixed now!

**Comment by mcweenysean** [comment]
great - thanks! Permissions to write to the remote machine got messed up so I'm waiting on Zach so I can push all these changes to live. Validation paper is getting close.
